name: Android CI

#on:
#  pull_request:
#    branches:
#      - main

on: workflow_dispatch

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache Android SDK
        uses: actions/cache@v4
        with:
          path: |
            /usr/local/lib/android/sdk/platform-tools
            /usr/local/lib/android/sdk/build-tools
          key: ${{ runner.os }}-android-sdk-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Execute build
        id: build
        run: ./gradlew build --no-daemon --profile

      - name: zip build reports
        id: zipBuildReports
        run: cd build/reports && zip -r ../../build-reports.zip ./* && cd -

      - name: Upload build reports
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: build-reports.zip