name: Android CI

#on:
#  pull_request:
#    branches:
#      - main

on: workflow_dispatch

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Execute build
        id: build
        run: ./gradlew build --no-daemon --profile

      - name: Compress build report
        if: steps.build.outcome == 'success'
        id: compressBuildReport
        run: cd build/reports && zip -r ../../build-reports.zip ./* && cd -

      - name: Upload build reports
        if: steps.compressBuildReport.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: build-reports.zip